# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 72d2024eeb6325e266d0e50cc2ab82a379283b2f46e33b3fa43c076e89e671edcf5789f55576397a0f3b0040e4cf73d0643bb26782c330da0a7a7df7f913f393

test:
  secret_key_base: d9692d87294344f7f2f9abfa0c9580e3de05fa3ee18cfccf2e789a8c690e9813a1b6dc83e8571265353735eed8ffb65ba856ef7a6d7f093ab06e8cd16fde240e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
